networks:
  siib:
    name: siib
    enable_ipv6: false

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    networks:
      - siib
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: '1234'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '4G'
    logging:
      options:
        max-size: 100M
        max-file: "1"
    restart: unless-stopped
  app:
    build: 
      dockerfile: ./Dockerfile
      context: . 
    container_name: app
    env_file: ".env"
    depends_on:
      - postgres
    networks:
      - siib
    ports:
      - "8080:3000"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '4G'
    logging:
      options:
        max-size: 100M
        max-file: "1"
    working_dir: /app
    restart: unless-stopped

volumes:
  postgres: